version: '3.9'

services:
  api:
    build:
      args:
        REGISTRY_BASE: node
      context: .
    command: ['npm', 'run', 'start']
    volumes:
      - .:/home/site/wwwroot/
    ports:
      - '${APP_PORT:-4000}:${APP_PORT:-4000}'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432 # container links shares local network
      API_VERSION: 'development'
    links:
      - postgres

  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data: {}
