import { MigrationInterface, QueryRunner } from 'typeorm';

export class CertificateSeeder1659090373904 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`INSERT INTO "carbon_certificate" ("country","status", "owner_id")
        VALUES
        ('Colombia', 'AVAILABLE', null),
        ('Ireland', 'AVAILABLE', null),
        ('Democratic Republic of the Congo', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('Portugal', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('Mauritius', 'AVAILABLE', null),
        ('Portugal', 'AVAILABLE', null),
        ('Nicaragua', 'OWNED', 1),
        ('China', 'AVAILABLE', null),
        ('Philippines', 'AVAILABLE', null),
        ('Argentina', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Poland', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('France', 'AVAILABLE', null),
        ('France', 'OWNED', 3),
        ('France', 'OWNED', 5),
        ('China', 'AVAILABLE', null),
        ('Russia', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('Dominican Republic', 'AVAILABLE', null),
        ('Vietnam', 'AVAILABLE', null),
        ('South Korea', 'AVAILABLE', null),
        ('Uzbekistan', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('Nigeria', 'AVAILABLE', null),
        ('Spain', 'AVAILABLE', null),
        ('Costa Rica', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('Mexico', 'AVAILABLE', null),
        ('China', 'OWNED', 6),
        ('Philippines', 'AVAILABLE', null),
        ('Armenia', 'AVAILABLE', null),
        ('Macedonia', 'AVAILABLE', null),
        ('Iran', 'AVAILABLE', null),
        ('Japan', 'AVAILABLE', null),
        ('Brazil', 'AVAILABLE', null),
        ('France', 'AVAILABLE', null),
        ('Finland', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Argentina', 'AVAILABLE', null),
        ('Russia', 'AVAILABLE', null),
        ('Philippines', 'AVAILABLE', null),
        ('Sweden', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Croatia', 'AVAILABLE', null),
        ('Russia', 'AVAILABLE', null),
        ('Malaysia', 'AVAILABLE', null),
        ('Russia', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Dominican Republic', 'AVAILABLE', null),
        ('Portugal', 'AVAILABLE', null),
        ('Ireland', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('Jamaica', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Croatia', 'AVAILABLE', null),
        ('Colombia', 'AVAILABLE', null),
        ('Russia', 'AVAILABLE', null),
        ('Norway', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Argentina', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Finland', 'AVAILABLE', null),
        ('Pakistan', 'OWNED', 8),
        ('Sweden', 'AVAILABLE', null),
        ('Sweden', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('El Salvador', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Thailand', 'AVAILABLE', null),
        ('Portugal', 'AVAILABLE', null),
        ('Botswana', 'AVAILABLE', null),
        ('Russia', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Philippines', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('Sweden', 'AVAILABLE', null),
        ('Syria', 'AVAILABLE', null),
        ('China', 'AVAILABLE', null),
        ('Thailand', 'AVAILABLE', null),
        ('Ethiopia', 'AVAILABLE', null),
        ('Egypt', 'AVAILABLE', null),
        ('Argentina', 'AVAILABLE', null),
        ('Sweden', 'AVAILABLE', null),
        ('Indonesia', 'AVAILABLE', null),
        ('Sweden', 'AVAILABLE', null),
        ('Poland', 'AVAILABLE', null),
        ('Russia', 'AVAILABLE', null),
        ('Poland', 'AVAILABLE', null),
        ('Armenia', 'AVAILABLE', null),
        ('Portugal', 'AVAILABLE', null)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`TRUNCATE TABLE "carbon_certificate"`);
  }
}
